# Generated by Django 5.2.8 on 2025-11-29 04:20

import projectApis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_assigned', 'Task Assigned'), ('task_deleted', 'Task Deleted'), ('comment_added', 'Comment Added'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('document_uploaded', 'Document Uploaded'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('team_created', 'Team Created'), ('team_updated', 'Team Updated')], db_index=True, max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the activity')),
                ('target_name', models.CharField(help_text='Name of the target object', max_length=255)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data about the activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projectApis.models.document_upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('sprintsize', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='project_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('goal', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('active', 'Active'), ('backlog', 'Backlog')], default='created', max_length=10)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High')], default='normal', max_length=10)),
                ('size', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], default='m', max_length=2)),
                ('created_by', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='ai', max_length=10)),
                ('task_number', models.CharField(editable=False, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Task tags like design, frontend, backend, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
