# Generated by Django 5.2.8 on 2025-12-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
