# Generated by Django 5.2.8 on 2025-11-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0003_add_uuid_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
