# Generated by Django 4.2.16 on 2024-12-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0003_comment_task_delete_projectitem_comment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectApis.project'),
            preserve_default=False,
        ),
    ]
