# Generated by Django 5.2.8 on 2025-11-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0004_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='projectApis_created_80f243_idx',
            old_name='projectApis_created_idx1',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='projectApis_activit_fbd57c_idx',
            old_name='projectApis_activity_idx1',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='projectApis_user_id_aca57a_idx',
            old_name='projectApis_user_idx1',
        ),
        migrations.RenameIndex(
            model_name='activity',
            new_name='projectApis_project_8edb55_idx',
            old_name='projectApis_project_idx1',
        ),
    ]
