# Generated by Django 4.2.16 on 2024-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0004_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='ai', max_length=10),
        ),
    ]
