# Generated by Django 5.2.8 on 2025-11-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0005_add_uuid_to_sprint_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='llm_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='LLM-generated task identifier for tracking and preventing duplicates', max_length=100, null=True, unique=True),
        ),
    ]
