# Generated by Django 5.2.8 on 2025-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApis', '0006_add_llm_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, help_text='Project deadline for AI task prioritization', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='Project domain (e.g., E-commerce, Healthcare, Finance)', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text="Technology stack (e.g., ['React', 'Django', 'PostgreSQL'])"),
        ),
    ]
