# Generated by Django 5.2.8 on 2025-11-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_url_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='', help_text="User's role (e.g., Backend Engineer, Frontend Developer, DevOps Engineer)", max_length=100),
        ),
    ]
