# Generated by Django 5.2.8 on 2025-11-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teaminvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['team', 'email', 'status'], name='users_teami_team_id_64b6de_idx'),
        ),
    ]
