# Generated by Django 5.2.8 on 2025-11-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teaminvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
