export enum URLS {
  BASE_URL = "http://localhost:8000/",
  USER_INFO = "api/accounts/user/info/",
  USERS = "api/accounts/users/",
  ADD_MEMBER = "/add-member/",
  REMOVE_MEMBER = "/remove-member/",
  LOGIN = "api/accounts/login/",
  REGISTER = "api/accounts/register/",
  PROJECTS = "api/project-management/projects/",
  ASSIGN_TEAM = "assign-team/",
  TEAMS = "api/accounts/teams/",
  PROJECTS_UPLOAD = "api/project-management/upload/",
  PROJECTS_VIEW = "api/project-management/view/",
  TASK = "api/project-management/tasks/",
  TASKS_BY_PROJECT = "api/project-management/projects/",
  TASKS_PATCH = "api/project-management/tasks-patch/",
  TASK_TRIGGER = "api/project-management/trigger/",
}
